name: zspace
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: ">=2.16.0 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    flame: ^1.2.0
    cupertino_icons: ^1.0.2
    email_validator: ^2.0.1
    dartz: ^0.10.1
    equatable: ^2.0.3
    internet_connection_checker: ^0.0.1+3
    google_fonts: ^2.3.1
    hive: ^2.0.4
    hive_flutter: ^1.1.0
    dio: ^4.0.4
    stacked: ^2.3.0
    get_it: ^7.2.0
    flutter_screenutil: ^5.2.0
    intl: ^0.17.0
    introduction_screen: ^3.0.0
    path_provider: ^2.0.9
    rest_api_package:
        path: ./rest_api_package
    font_awesome_flutter: ^10.1.0
    auto_size_text: ^3.0.0
    flutter_glow: ^0.2.0
    get: ^4.6.1
    decorated_icon: ^1.2.1
    lottie: ^1.3.0
    flutter_swiper_null_safety: ^1.0.2
    connectivity_plus: ^2.2.1
    cookie_jar: ^3.0.1
    flutter_vibrate: ^1.3.0
    carousel_slider: ^4.0.0
    dots_indicator: ^2.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    mockito: ^5.1.0
    build_runner: ^2.1.7
    hive_generator: ^1.1.0
    dcdg: ^4.0.1
flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/images/ships/
        - assets/images/lasers/
        - assets/images/rockets/
        - assets/images/explosions/
        - assets/images/maps/
        - assets/images/shields/
        - assets/images/portals/
        - assets/images/items/
        - assets/images/mines/
        - assets/images/planets/
        - assets/images/asteroids/
        - assets/images/utilities/
        - assets/lotties/

    # To add assets to your application, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
